export default function() {
	return [
		{
			"id": 1,
			"month": 1,
			"index": 1,
			"normal": true,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": false,
			"bright": false
		},
		{
			"id": 2,
			"month": 1,
			"index": 2,
			"normal": true,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": false,
			"bright": false
		},
		{
			"id": 3,
			"month": 1,
			"index": 3,
			"normal": false,
			"redRibbon": true,
			"blueRibbon": false,
			"poetryRibbon": true,
			"animal": false,
			"bright": false
		},
		{
			"id": 4,
			"month": 1,
			"index": 4,
			"normal": false,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": false,
			"bright": true
		},
		{
			"id": 5,
			"month": 2,
			"index": 1,
			"normal": true,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": false,
			"bright": false
		},
		{
			"id": 6,
			"month": 2,
			"index": 2,
			"normal": true,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": false,
			"bright": false
		},
		{
			"id": 7,
			"month": 2,
			"index": 3,
			"normal": false,
			"redRibbon": true,
			"blueRibbon": false,
			"poetryRibbon": true,
			"animal": false,
			"bright": false
		},
		{
			"id": 8,
			"month": 2,
			"index": 4,
			"normal": false,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": true,
			"bright": false
		},
		{
			"id": 9,
			"month": 3,
			"index": 1,
			"normal": true,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": false,
			"bright": false
		},
		{
			"id": 10,
			"month": 3,
			"index": 2,
			"normal": true,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": false,
			"bright": false
		},
		{
			"id": 11,
			"month": 3,
			"index": 3,
			"normal": false,
			"redRibbon": true,
			"blueRibbon": false,
			"poetryRibbon": true,
			"animal": false,
			"bright": false
		},
		{
			"id": 12,
			"month": 3,
			"index": 4,
			"normal": false,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": false,
			"bright": true
		},
		{
			"id": 13,
			"month": 4,
			"index": 1,
			"normal": true,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": false,
			"bright": false
		},
		{
			"id": 14,
			"month": 4,
			"index": 2,
			"normal": true,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": false,
			"bright": false
		},
		{
			"id": 15,
			"month": 4,
			"index": 3,
			"normal": false,
			"redRibbon": true,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": false,
			"bright": false
		},
		{
			"id": 16,
			"month": 4,
			"index": 4,
			"normal": false,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": true,
			"bright": false
		},
		{
			"id": 17,
			"month": 5,
			"index": 1,
			"normal": true,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": false,
			"bright": false
		},
		{
			"id": 18,
			"month": 5,
			"index": 2,
			"normal": true,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": false,
			"bright": false
		},
		{
			"id": 19,
			"month": 5,
			"index": 3,
			"normal": false,
			"redRibbon": true,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": false,
			"bright": false
		},
		{
			"id": 20,
			"month": 5,
			"index": 4,
			"normal": false,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": true,
			"bright": false
		},
		{
			"id": 21,
			"month": 6,
			"index": 1,
			"normal": true,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": false,
			"bright": false
		},
		{
			"id": 22,
			"month": 6,
			"index": 2,
			"normal": true,
			"redRibbon": true,
			"blueRibbon": true,
			"poetryRibbon": false,
			"animal": false,
			"bright": false
		},
		{
			"id": 23,
			"month": 6,
			"index": 3,
			"normal": false,
			"redRibbon": false,
			"blueRibbon": true,
			"poetryRibbon": false,
			"animal": false,
			"bright": false
		},
		{
			"id": 24,
			"month": 6,
			"index": 4,
			"normal": false,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": true,
			"bright": false
		},
		{
			"id": 25,
			"month": 7,
			"index": 1,
			"normal": true,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": false,
			"bright": false
		},
		{
			"id": 26,
			"month": 7,
			"index": 2,
			"normal": true,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": false,
			"bright": false
		},
		{
			"id": 27,
			"month": 7,
			"index": 3,
			"normal": false,
			"redRibbon": true,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": false,
			"bright": false
		},
		{
			"id": 28,
			"month": 7,
			"index": 4,
			"normal": false,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": true,
			"bright": false
		},
		{
			"id": 29,
			"month": 8,
			"index": 1,
			"normal": true,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": false,
			"bright": false
		},
		{
			"id": 30,
			"month": 8,
			"index": 2,
			"normal": true,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": false,
			"bright": false
		},
		{
			"id": 31,
			"month": 8,
			"index": 3,
			"normal": false,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": true,
			"bright": false
		},
		{
			"id": 32,
			"month": 8,
			"index": 4,
			"normal": false,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": false,
			"bright": true
		},
		{
			"id": 33,
			"month": 9,
			"index": 1,
			"normal": true,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": false,
			"bright": false
		},
		{
			"id": 34,
			"month": 9,
			"index": 2,
			"normal": true,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": false,
			"bright": false
		},
		{
			"id": 35,
			"month": 9,
			"index": 3,
			"normal": false,
			"redRibbon": false,
			"blueRibbon": true,
			"poetryRibbon": false,
			"animal": false,
			"bright": false
		},
		{
			"id": 36,
			"month": 9,
			"index": 4,
			"normal": true,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": true,
			"bright": false
		},
		{
			"id": 37,
			"month": 10,
			"index": 1,
			"normal": true,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": false,
			"bright": false
		},
		{
			"id": 38,
			"month": 10,
			"index": 2,
			"normal": true,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": false,
			"bright": false
		},
		{
			"id": 39,
			"month": 10,
			"index": 3,
			"normal": false,
			"redRibbon": false,
			"blueRibbon": true,
			"poetryRibbon": true,
			"animal": false,
			"bright": false
		},
		{
			"id": 40,
			"month": 10,
			"index": 4,
			"normal": false,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": true,
			"bright": false
		},
		{
			"id": 41,
			"month": 11,
			"index": 1,
			"normal": true,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": false,
			"bright": false
		},
		{
			"id": 42,
			"month": 11,
			"index": 2,
			"normal": false,
			"redRibbon": true,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": false,
			"bright": false
		},
		{
			"id": 43,
			"month": 11,
			"index": 3,
			"normal": false,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": true,
			"bright": false
		},
		{
			"id": 44,
			"month": 11,
			"index": 4,
			"normal": false,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": false,
			"bright": true
		},
		{
			"id": 45,
			"month": 12,
			"index": 1,
			"normal": true,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": false,
			"bright": false
		},
		{
			"id": 46,
			"month": 12,
			"index": 2,
			"normal": true,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": false,
			"bright": false
		},
		{
			"id": 47,
			"month": 12,
			"index": 3,
			"normal": true,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": false,
			"bright": false
		},
		{
			"id": 48,
			"month": 12,
			"index": 4,
			"normal": false,
			"redRibbon": false,
			"blueRibbon": false,
			"poetryRibbon": false,
			"animal": false,
			"bright": true
		}
	];
}
